### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by ChehST** [ViktorSvertoka/site-html#5]
Интересно стало посмотреть проект, обнаружил фичу с отзывчивостью дизайна)
Некритично, но когда с мобильного представления жмешь на тогглер то открывается навбар, круто.
Однако если представление изменилось на десктопное этот навбар остается растянутым на весь экран и появляется ещё одна вертикальная скрол полоска.

**Comment by ViktorSvertoka** [comment]
Это были первые пробы)
